// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetailModule: typeof import('./components/DetailModule.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavItem: typeof import('./components/TopNavItem.vue')['default']
    TopSubNavItem: typeof import('./components/TopSubNavItem.vue')['default']
  }
}
